### ISSUE TITLE
Option to make event 1008 in NPCs move their mouth?

### ISSUE THREAD

**Issue by Droooga** [SamVanheer/HalfLifeAssetManager#272] opened 2023-02-03 18:08 UTC

**Comment by SamVanheer** [comment] 2023-02-06 20:50
The mouth is currently moved by the Bone Controllers panel so this would require an option to override that. Additionally sounds would need to be more closely tied to the object that emits them to feed the relevant information back to it, so this isn't easy to implement. I'll consider it for a future update.

**Comment by SamVanheer** [comment] 2024-03-03 22:20
Duplicate of #93

**Closed by SamVanheer** 2024-03-03 22:20 UTC
Labels: duplicate
